# Generated by Django 4.2.13 on 2024-05-22 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    replaces = [('gallery', '0002_alter_picture_image')]

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='wagtailimages.image',
            ),
        ),
    ]
