# Generated by Django 4.2.13 on 2024-05-30 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_img_tabl_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
    ]
