# Generated by Django 4.2.13 on 2024-06-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('blog', '0003_remove_blogpage_date'), ('blog', '0004_alter_blogpage_intro_alter_blogpage_thumb')]

    dependencies = [
        ('wagtailimages', '0026_delete_uploadedimage'),
        ('blog', '0002_img_tabl_ref'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='date',
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
