# Generated by Django 4.2.13 on 2024-06-05 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('blog', '0003_blog_mod_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.tfimage'),
        ),
    ]
