# Generated by Django 4.2.13 on 2024-06-06 05:59

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_blogpage_thumb"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="wp_block_json",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_link",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_normalized_styles",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_post_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_post_meta",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_post_type",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_processed_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="wp_raw_content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="blogpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("rich_text", wagtail.blocks.RichTextBlock()),
                    (
                        "heading",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "text",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                (
                                    "importance",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("h1", "H1"),
                                            ("h2", "H2"),
                                            ("h3", "H3"),
                                            ("h4", "H4"),
                                            ("h5", "H5"),
                                            ("h6", "H6"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "image",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                                ("link", wagtail.blocks.URLBlock(required=False)),
                                (
                                    "alignment",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("left", "Left"),
                                            ("right", "Right"),
                                            ("center", "Center"),
                                        ]
                                    ),
                                ),
                            ]
                        ),
                    ),
                    (
                        "block_quote",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "quote",
                                    wagtail.blocks.CharBlock(form_classname="title"),
                                ),
                                (
                                    "attribution",
                                    wagtail.blocks.CharBlock(required=False),
                                ),
                            ]
                        ),
                    ),
                    ("raw_html", wagtail.blocks.RawHTMLBlock()),
                ]
            ),
        ),
    ]
