# Generated by Django 4.2.13 on 2024-06-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogpage_wp_block_json_blogpage_wp_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_block_json",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_link",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_normalized_styles",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_post_id",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_post_meta",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_post_type",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_processed_content",
        ),
        migrations.RemoveField(
            model_name="blogpage",
            name="wp_raw_content",
        ),
    ]
