# Generated by Django 4.2.16 on 2024-11-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tfimage_description'),
        ('blog', '0006_remove_blogpage_wp_block_json_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.tfimage'),
        ),
    ]
