# Generated by Django 4.2.16 on 2024-11-30 15:57

import base.models
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    replaces = [('blog', '0008_blogpage_authors_blogpage_date'), ('blog', '0009_remove_blogpage_authors_alter_blogpage_date_and_more'), ('blog', '0010_bloginvolvementinfo_id_and_more'), ('blog', '0011_remove_blogpage_date'), ('blog', '0012_alter_bloginvolvementinfo_author')]

    dependencies = [
        ('base', '0004_alter_tfauthor_id'),
        ('base', '0003_tfauthor'),
        ('blog', '0007_alter_blogpage_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInvolvementInfo',
            fields=[
                ('blog', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='blog.blogpage')),
                ('author', models.OneToOneField(default=base.models.TFAuthor, on_delete=django.db.models.deletion.DO_NOTHING, to='base.tfauthor')),
                ('id', models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
