# Generated by Django 4.2.16 on 2024-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpage_authors_blogpage_date_squashed_0012_alter_bloginvolvementinfo_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloginvolvementinfo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
