# Generated by Django 4.2.16 on 2024-11-30 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_tfimage_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TFAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127, verbose_name='name')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.tfimage')),
            ],
            options={
                'verbose_name_plural': 'Authors',
            },
        ),
    ]
