# Generated by Django 4.2.16 on 2024-11-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_tfauthor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfauthor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
