fragment DefaultImageView on TFImage {
  id
  url
  rendition(width: 1200, height: 630, format: "jpeg", jpegquality: 85) {
    id
    url
    width
    height
  }
  srcSet(sizes: [768, 1080], format: "webp")
  width
  height
}

fragment BlogPageOuterView on BlogPage {
  id
  slug
  title
  seoTitle
  thumb {
    ...DefaultImageView
  }
}

fragment BlogPageInnerView on BlogPage {
  body {
    ... on StreamFieldInterface {
      blockType
    }
    ... on RichTextBlock {
      value
    }
    ... on ImageBlock {
      caption
      link
      alignment
      image {
        ...DefaultImageView
      }
    }
    ... on QuoteBlock {
      quote
      attribution
    }
    ... on HeadingBlock {
      text
      importance
    }
  }
}

fragment GalleryOuterView on Picture {
  id
  cap
  image {
    ...DefaultImageView
  }
  imageDate
}

query GalleryListView {
  pages(contentType: "gallery.Picture") {
    ...GalleryOuterView
  }
}

query GalleryPaginatedListView(
  $offset: PositiveInt
  $limit: PositiveInt
  $order: String
) {
  pages(
    contentType: "gallery.Picture"
    offset: $offset
    limit: $limit
    order: $order
  ) {
    ...GalleryOuterView
  }
}

query BlogListView {
  pages(contentType: "blog.BlogPage") {
    ...BlogPageOuterView
  }
}

query BlogPaginatedListView($offset: PositiveInt, $limit: PositiveInt, $order: String) {
  pages(
    contentType: "blog.BlogPage"
    offset: $offset
    limit: $limit
    order: $order
  ) {
    ...BlogPageOuterView
  }
}

query BlogPreviewView($token: String) {
  page(id: 0, token: $token) {
    ...BlogPageOuterView
    ...BlogPageInnerView
  }
}

query BlogLiveView($slug: String) {
  page(slug: $slug) {
    ...BlogPageOuterView
    ...BlogPageInnerView
  }
}
