fragment DefaultImageView on TFImage {
  id
  url
  rendition(width: 1200, height: 630, format: "jpeg", jpegquality: 85) {
    id
    url
    width
    height
  }
  srcSet(sizes: [768, 1080], format: "webp")
  width
  height
}

fragment BlogPageOuterView on BlogPage {
  id
  slug
  title
  intro
  seoTitle
  involved {
    id
    name
    image {
      url
      srcSet(sizes: [8, 16, 32, 64], format: "webp")
    }
  }
  thumb {
    ...DefaultImageView
  }
}

fragment BlogPageInnerView on BlogPage {
  body {
    ... on StreamFieldInterface {
      blockType
    }
    ... on RichTextBlock {
      value
    }
    ... on ImageBlock {
      caption
      link
      alignment
      image {
        ...DefaultImageView
      }
    }
    ... on QuoteBlock {
      quote
      attribution
    }
    ... on HeadingBlock {
      text
      importance
    }
  }
}

fragment GalleryOuterView on Picture {
  id
  title
  cap
  image {
    ...DefaultImageView
  }
  imageDate
}

fragment PaginationView on PaginationType {
  total
  count
  perPage
  currentPage
  prevPage
  nextPage
  totalPages
}

# query GalleryListView {
#   pictures(page: 1, perPage: 10) {
#     pagination {
#       ...PaginationView
#     }
#     items {
#       ...GalleryOuterView
#     }
#   }
# }

query GalleryPaginatedListView(
  $page: PositiveInt
  $perPage: PositiveInt
  $order: String
) {
  pictures(page: $page, perPage: $perPage, order: $order) {
    pagination {
      ...PaginationView
    }
    items {
      ...GalleryOuterView
    }
  }
}

# query BlogListView {
#   blogs(page: 1, perPage: 10) {
#     pagination {
#       ...PaginationView
#     }
#     items {
#       ...BlogPageOuterView
#     }
#   }
# }

query BlogPaginatedListView(
  $page: PositiveInt
  $perPage: PositiveInt
  $order: String
) {
  blogs(page: $page, perPage: $perPage, order: $order) {
    pagination {
      ...PaginationView
    }
    items {
      ...BlogPageOuterView
    }
  }
}

query BlogPreviewView($token: String) {
  blog(token: $token) {
    ...BlogPageOuterView
    ...BlogPageInnerView
  }
}

query BlogLiveView($slug: String) {
  blog(slug: $slug) {
    ...BlogPageOuterView
    ...BlogPageInnerView
  }
}
